
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, messagebox, Button, PhotoImage
from frame9 import open_frame9


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / "assets" / "frame8"


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def username_exists(username):
    with open('accounts.txt', 'r') as file:
        lines = file.readlines()
        usernames = [lines[i].strip() for i in range(0, len(lines), 4)]
        if username in usernames:
            window.destroy()
            open_frame9(username)
        else:
            messagebox.showerror("Error", "User does not exist.")

def open_frame8():
        
    def back():
        from frame1 import open_frame1
        window.destroy()
        open_frame1()
    
    global window
    window = Tk()

    window.geometry("978x640")
    window.configure(bg = "#DAD4BF")

    canvas = Canvas(
        window,
        bg = "#DAD4BF",
        height = 640,
        width = 978,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        74.0,
        640.0,
        fill="#C3C3A9",
        outline="")

    canvas.create_rectangle(
        0.0,
        0.0,
        978.0,
        67.0,
        fill="#B5B59D",
        outline="")

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        37.0,
        33.0,
        image=image_image_1
    )

    canvas.create_text(
        74.0,
        16.0,
        anchor="nw",
        text="Key Notebook",
        fill="#000000",
        font=("Amaranth Regular", 32 * -1)
    )

    canvas.create_rectangle(
        378.0,
        207.0,
        719.0,
        615.0,
        fill="#DAD4BF",
        outline="")

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        533.5,
        343.5,
        image=entry_image_1
    )
    frame8_username = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0,
        font=("Andada Pro", 12),
    )
    frame8_username.place(
        x=405.0,
        y=311.0,
        width=257.0,
        height=61.0
    )

    canvas.create_text(
        400.0,
        130.0,
        anchor="nw",
        text="Forgot Password",
        fill="#000000",
        font=("RobotoSerifNormalRoman Regular", 36 * -1)
    )

    canvas.create_text(
        409.0,
        293.0,
        anchor="nw",
        text="enter username/email",
        fill="#000000",
        font=("AndadaProRoman Regular", 13 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    submit_button = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:username_exists(frame8_username.get()),
        relief="flat"
    )
    submit_button.place(
        x=413.0,
        y=482.0,
        width=244.0,
        height=67.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    back_button = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: back(),
        relief="flat"
    )
    back_button.place(
        x=16.0,
        y=582.0,
        width=42.0,
        height=42.0
    )
    window.resizable(False, False)
    window.mainloop()