
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
import os

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Button, PhotoImage
from frame7 import open_frame7

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / "assets" / "frame5"

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def user_logout():
    from frame1 import open_frame1
    if os.path.exists("current_user.txt"):
        os.remove("current_user.txt")
        window.destroy()
        open_frame1()
    else:
        print("File does not exist")

def change_pass():
    window.destroy()
    open_frame7()

def open_notebook():
    from frame4 import open_frame4
    window.destroy()
    open_frame4()

def open_frame5():
    global window
    window = Tk()

    window.geometry("978x640")
    window.configure(bg = "#DAD4BF")


    canvas = Canvas(
        window,
        bg = "#DAD4BF",
        height = 640,
        width = 978,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        74.0,
        640.0,
        fill="#C3C3A9",
        outline="")

    canvas.create_rectangle(
        0.0,
        0.0,
        978.0,
        67.0,
        fill="#B5B59D",
        outline="")

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        37.0,
        33.0,
        image=image_image_1
    )

    canvas.create_text(
        74.0,
        16.0,
        anchor="nw",
        text="Key Notebook",
        fill="#000000",
        font=("Amaranth Regular", 32 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button 1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=16.0,
        y=590.0,
        width=42.0,
        height=42.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    notebook_button2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_notebook(),
        relief="flat"
    )
    notebook_button2.place(
        x=15.0,
        y=83.0,
        width=45.0,
        height=45.0
    )

    canvas.create_text(
        460.0,
        161.0,
        anchor="nw",
        text="Settings",
        fill="#000000",
        font=("RobotoSlab Regular", 36 * -1)
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    logout_button = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: user_logout(),
        relief="flat"
    )
    logout_button.place(
        x=442.0,
        y=483.0,
        width=163.0,
        height=46.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    changePass_button = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: change_pass(),
        relief="flat"
    )
    changePass_button.place(
        x=573.0,
        y=246.0,
        width=114.0,
        height=31.0
    )

    canvas.create_text(
        306.0,
        241.0,
        anchor="nw",
        text="Change password",
        fill="#000000",
        font=("AbhayaLibre Bold", 20 * -1)
    )
    window.resizable(False, False)
    window.mainloop()