
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\taylo\OneDrive\Desktop\VS_CODE\Python\CS 2520\Projects\Key Notebook\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("978x640")
window.configure(bg = "#DAD4BF")


canvas = Canvas(
    window,
    bg = "#DAD4BF",
    height = 640,
    width = 978,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    74.0,
    640.0,
    fill="#C3C3A9",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    978.0,
    67.0,
    fill="#B5B59D",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    37.0,
    33.0,
    image=image_image_1
)

canvas.create_text(
    74.0,
    16.0,
    anchor="nw",
    text="Key Notebook",
    fill="#000000",
    font=("Amaranth Regular", 32 * -1)
)

canvas.create_rectangle(
    378.0,
    207.0,
    719.0,
    473.0,
    fill="#DAD4BF",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    534.5,
    400.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Andada Pro", 12)
)
entry_1.place(
    x=406.0,
    y=368.0,
    width=257.0,
    height=61.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    534.5,
    275.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Andada Pro", 12)
)
entry_2.place(
    x=406.0,
    y=242.0,
    width=257.0,
    height=61.0
)

canvas.create_text(
    414.0,
    130.0,
    anchor="nw",
    text="Create Account",
    fill="#000000",
    font=("RobotoSerifNormalRoman Regular", 36 * -1)
)

canvas.create_text(
    410.0,
    225.0,
    anchor="nw",
    text="email or username",
    fill="#000000",
    font=("AndadaProRoman Regular", 13 * -1)
)

canvas.create_text(
    410.0,
    350.0,
    anchor="nw",
    text="password",
    fill="#000000",
    font=("AndadaProRoman Regular", 13 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=413.0,
    y=473.0,
    width=244.0,
    height=67.0
)
window.resizable(False, False)
window.mainloop()
